"""4th

Revision ID: 0f741ccae236
Revises: 6302b865b6eb
Create Date: 2025-05-05 01:39:18.246039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f741ccae236'
down_revision = '6302b865b6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('requested_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processed_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], name='document_requests_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_requests_pkey')
    )
    # ### end Alembic commands ###
