"""5th

Revision ID: 161edeefe2ac
Revises: b1ca452d49cf
Create Date: 2025-05-05 02:58:52.872690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161edeefe2ac'
down_revision = 'b1ca452d49cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_room_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_room_bookings', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
