"""updated models

Revision ID: 2b680a614ed0
Revises: eb86ce350d09
Create Date: 2025-05-06 08:48:26.277862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b680a614ed0'
down_revision = 'eb86ce350d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blacklist')
    with op.batch_alter_table('document_request', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('document_request_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('document_request_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('fee_clearances', schema=None) as batch_op:
        batch_op.drop_column('hostel_clearance')
        batch_op.drop_column('fee_clearance')

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_column('units')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('receipt_number')
        batch_op.drop_column('payment_status')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('capacity')
        batch_op.drop_column('current_occupancy')
        batch_op.drop_column('room_type')

    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_constraint('semesters_fee_structure_id_fkey', type_='foreignkey')
        batch_op.drop_column('fee_structure_id')

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.drop_column('phone_number')
        batch_op.drop_column('gender')

    with op.batch_alter_table('student_room_bookings', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    with op.batch_alter_table('student_room_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('phone')

    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_structure_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('semesters_fee_structure_id_fkey', 'fee_structures', ['fee_structure_id'], ['id'])

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('current_occupancy', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('receipt_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units', sa.VARCHAR(length=15), autoincrement=False, nullable=False))

    with op.batch_alter_table('fee_clearances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_clearance', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hostel_clearance', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('document_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('document_request_student_id_fkey', 'student_profiles', ['student_id'], ['id'])
        batch_op.create_foreign_key('document_request_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='token_blacklist_pkey'),
    sa.UniqueConstraint('jti', name='token_blacklist_jti_key')
    )
    # ### end Alembic commands ###
