"""empty message

Revision ID: 31336cc70f9c
Revises: f31ef314d48e
Create Date: 2025-05-11 15:38:31.522064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31336cc70f9c'
down_revision = 'f31ef314d48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
