"""return back to normal

Revision ID: 409b1abf2469
Revises: 
Create Date: 2025-05-10 10:07:26.994499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409b1abf2469'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fees')
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_constraint('grade_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grade_student_id_fkey', 'student_profiles', ['student_id'], ['id'])

    op.create_table('fees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], name='fees_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fees_pkey')
    )
    # ### end Alembic commands ###
