"""empty message

Revision ID: 4146c07a34bf
Revises: b7716e033ed9
Create Date: 2025-05-11 15:33:41.986015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4146c07a34bf'
down_revision = 'b7716e033ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_occupancts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('current_occupancts')

    # ### end Alembic commands ###
