"""update

Revision ID: 45271b952043
Revises: 7e8e53245444
Create Date: 2025-05-05 21:41:23.676639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45271b952043'
down_revision = '7e8e53245444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.alter_column('fee_structures_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.alter_column('fee_structures_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
