"""Updated FeeStructure and Semester models

Revision ID: 45b6d293f76b
Revises: 45271b952043
Create Date: 2025-05-05 22:11:46.917487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b6d293f76b'
down_revision = '45271b952043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_structure_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('semesters_fee_structures_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'fee_structures', ['fee_structure_id'], ['id'])
        batch_op.drop_column('fee_structures_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_structures_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('semesters_fee_structures_id_fkey', 'fee_structures', ['fee_structures_id'], ['id'])
        batch_op.drop_column('fee_structure_id')

    # ### end Alembic commands ###
