"""updated

Revision ID: 5664d8bb3c5a
Revises: 2b680a614ed0
Create Date: 2025-05-06 10:11:37.872115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5664d8bb3c5a'
down_revision = '2b680a614ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecturer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lecturer_profiles', ['lecturer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lecturer_id')

    # ### end Alembic commands ###
