"""empty message

Revision ID: 5adfc1428672
Revises: a48e1dfa293f
Create Date: 2025-05-11 00:39:22.830028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adfc1428672'
down_revision = 'a48e1dfa293f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_clearances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('amount_due', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_clearances', schema=None) as batch_op:
        batch_op.drop_column('amount_due')
        batch_op.drop_column('student_name')

    # ### end Alembic commands ###
