"""Updated payment to add receipt_number

Revision ID: 66bd049a33d9
Revises: 45b6d293f76b
Create Date: 2025-05-05 22:28:17.989036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bd049a33d9'
down_revision = '45b6d293f76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_number', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('receipt_number')

    # ### end Alembic commands ###
