"""update

Revision ID: 67bc9c1e9a81
Revises: 3a861ac05162
Create Date: 2025-05-05 21:25:23.404921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67bc9c1e9a81'
down_revision = '3a861ac05162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_structures_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'fee_structures', ['fee_structures_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fee_structures_id')

    # ### end Alembic commands ###
