"""update

Revision ID: 728428c96d21
Revises: e540c5c79340
Create Date: 2025-05-05 21:14:45.038753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728428c96d21'
down_revision = 'e540c5c79340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
