"""update

Revision ID: 7e8e53245444
Revises: 67bc9c1e9a81
Create Date: 2025-05-05 21:38:11.811920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8e53245444'
down_revision = '67bc9c1e9a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.drop_constraint('fee_structures_semester_id_fkey', type_='foreignkey')
        batch_op.drop_column('semester_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fee_structures_semester_id_fkey', 'semesters', ['semester_id'], ['id'])

    # ### end Alembic commands ###
