"""Update fee structure to use courses, hostels, and semesters

Revision ID: 8446bf8af986
Revises: f0f51acab012
Create Date: 2025-05-06 20:07:41.743083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8446bf8af986'
down_revision = 'f0f51acab012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hostel_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('semester_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'semesters', ['semester_id'], ['id'])
        batch_op.create_foreign_key(None, 'hostels', ['hostel_id'], ['id'])
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.drop_column('program')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('semester_id')
        batch_op.drop_column('hostel_id')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
