"""create assignment

Revision ID: 8f6ed1e752c0
Revises: 0a62cb42bd4f
Create Date: 2025-05-08 15:15:57.812450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6ed1e752c0'
down_revision = '0a62cb42bd4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint('assignments_submitted_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('assignments_lecturer_id_fkey', type_='foreignkey')
        batch_op.drop_column('submitted_by')
        batch_op.drop_column('lecturer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecturer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('submitted_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('assignments_lecturer_id_fkey', 'users', ['lecturer_id'], ['id'])
        batch_op.create_foreign_key('assignments_submitted_by_fkey', 'users', ['submitted_by'], ['id'])

    # ### end Alembic commands ###
