"""Updated payment to add payment_status

Revision ID: 985503be4b9f
Revises: 66bd049a33d9
Create Date: 2025-05-05 22:30:24.147997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985503be4b9f'
down_revision = '66bd049a33d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
