"""create assignment

Revision ID: a214070ddaea
Revises: 8f6ed1e752c0
Create Date: 2025-05-08 15:19:49.749133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a214070ddaea'
down_revision = '8f6ed1e752c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecturer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['lecturer_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['submitted_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('submitted_by_id')
        batch_op.drop_column('lecturer_id')

    # ### end Alembic commands ###
