"""empty message

Revision ID: b8b3b1663168
Revises: 5adfc1428672
Create Date: 2025-05-11 12:33:22.068571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b3b1663168'
down_revision = '5adfc1428672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_clearances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_clearances', schema=None) as batch_op:
        batch_op.drop_column('program')

    # ### end Alembic commands ###
