"""empty message

Revision ID: d00a639495da
Revises: b8b3b1663168
Create Date: 2025-05-11 15:24:04.108099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00a639495da'
down_revision = 'b8b3b1663168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
