"""updated models

Revision ID: eb86ce350d09
Revises: d237f36565ce
Create Date: 2025-05-06 08:30:59.438568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb86ce350d09'
down_revision = 'd237f36565ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    with op.batch_alter_table('document_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('document_request_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'student_profiles', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('fee_clearances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostel_clearance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fee_clearance', sa.Boolean(), nullable=True))

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units', sa.String(length=15), nullable=False))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('current_occupancy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('room_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_structure_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fee_structures', ['fee_structure_id'], ['id'])

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.drop_column('phone')

    with op.batch_alter_table('student_room_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('student_room_bookings', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('phone_number')
        batch_op.drop_column('gender')

    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fee_structure_id')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('room_type')
        batch_op.drop_column('current_occupancy')
        batch_op.drop_column('capacity')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('receipt_number')

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_column('units')

    with op.batch_alter_table('fee_clearances', schema=None) as batch_op:
        batch_op.drop_column('fee_clearance')
        batch_op.drop_column('hostel_clearance')

    with op.batch_alter_table('document_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('document_request_student_id_fkey', 'users', ['student_id'], ['id'])
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('user_id')

    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
