"""empty message

Revision ID: f31ef314d48e
Revises: 4146c07a34bf
Create Date: 2025-05-11 15:37:25.026667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31ef314d48e'
down_revision = '4146c07a34bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_occupants', sa.Integer(), nullable=True))
        batch_op.drop_column('current_occupancts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_occupancts', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('current_occupants')

    # ### end Alembic commands ###
