"""Add hostel_clearance to FeeClearance

Revision ID: f9194795ad90
Revises: 985503be4b9f
Create Date: 2025-05-05 22:33:21.978763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9194795ad90'
down_revision = '985503be4b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_clearances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostel_clearance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fee_clearance', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_clearances', schema=None) as batch_op:
        batch_op.drop_column('fee_clearance')
        batch_op.drop_column('hostel_clearance')

    # ### end Alembic commands ###
